// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TenantServiceGroupCreateVerticalEnum - A token that identifies the business vertical supported by the SASE
// products managed by this TSG.
type TenantServiceGroupCreateVerticalEnum string

const (
	TenantServiceGroupCreateVerticalEnumHighTech                      TenantServiceGroupCreateVerticalEnum = "High Tech"
	TenantServiceGroupCreateVerticalEnumEducation                     TenantServiceGroupCreateVerticalEnum = "Education"
	TenantServiceGroupCreateVerticalEnumManufacturing                 TenantServiceGroupCreateVerticalEnum = "Manufacturing"
	TenantServiceGroupCreateVerticalEnumHospitality                   TenantServiceGroupCreateVerticalEnum = "Hospitality"
	TenantServiceGroupCreateVerticalEnumProfessionalAndLegalServices  TenantServiceGroupCreateVerticalEnum = "Professional & Legal Services"
	TenantServiceGroupCreateVerticalEnumWholesaleAndRetail            TenantServiceGroupCreateVerticalEnum = "Wholesale & Retail"
	TenantServiceGroupCreateVerticalEnumFinance                       TenantServiceGroupCreateVerticalEnum = "Finance"
	TenantServiceGroupCreateVerticalEnumTelecommunications            TenantServiceGroupCreateVerticalEnum = "Telecommunications"
	TenantServiceGroupCreateVerticalEnumStateAndLocalGovernment       TenantServiceGroupCreateVerticalEnum = "State & Local Government"
	TenantServiceGroupCreateVerticalEnumTransportationAndLogistics    TenantServiceGroupCreateVerticalEnum = "Transportation & Logistics"
	TenantServiceGroupCreateVerticalEnumFederalGovernment             TenantServiceGroupCreateVerticalEnum = "Federal Government"
	TenantServiceGroupCreateVerticalEnumMediaAndEntertainment         TenantServiceGroupCreateVerticalEnum = "Media & Entertainment"
	TenantServiceGroupCreateVerticalEnumNonclassifiableEstablishments TenantServiceGroupCreateVerticalEnum = "Nonclassifiable Establishments"
	TenantServiceGroupCreateVerticalEnumHealthcare                    TenantServiceGroupCreateVerticalEnum = "Healthcare"
	TenantServiceGroupCreateVerticalEnumUtilitiesAndEnergy            TenantServiceGroupCreateVerticalEnum = "Utilities & Energy"
	TenantServiceGroupCreateVerticalEnumInsurance                     TenantServiceGroupCreateVerticalEnum = "Insurance"
	TenantServiceGroupCreateVerticalEnumAgriculture                   TenantServiceGroupCreateVerticalEnum = "Agriculture"
	TenantServiceGroupCreateVerticalEnumPharmaAndLifeSciences         TenantServiceGroupCreateVerticalEnum = "Pharma & Life Sciences"
	TenantServiceGroupCreateVerticalEnumConstruction                  TenantServiceGroupCreateVerticalEnum = "Construction"
	TenantServiceGroupCreateVerticalEnumAerospaceAndDefense           TenantServiceGroupCreateVerticalEnum = "Aerospace & Defense"
	TenantServiceGroupCreateVerticalEnumRealEstate                    TenantServiceGroupCreateVerticalEnum = "Real Estate"
	TenantServiceGroupCreateVerticalEnumRestaurantFoodIndustry        TenantServiceGroupCreateVerticalEnum = "Restaurant/Food Industry"
	TenantServiceGroupCreateVerticalEnumOther                         TenantServiceGroupCreateVerticalEnum = "Other"
)

func (e TenantServiceGroupCreateVerticalEnum) ToPointer() *TenantServiceGroupCreateVerticalEnum {
	return &e
}

func (e *TenantServiceGroupCreateVerticalEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "High Tech":
		fallthrough
	case "Education":
		fallthrough
	case "Manufacturing":
		fallthrough
	case "Hospitality":
		fallthrough
	case "Professional & Legal Services":
		fallthrough
	case "Wholesale & Retail":
		fallthrough
	case "Finance":
		fallthrough
	case "Telecommunications":
		fallthrough
	case "State & Local Government":
		fallthrough
	case "Transportation & Logistics":
		fallthrough
	case "Federal Government":
		fallthrough
	case "Media & Entertainment":
		fallthrough
	case "Nonclassifiable Establishments":
		fallthrough
	case "Healthcare":
		fallthrough
	case "Utilities & Energy":
		fallthrough
	case "Insurance":
		fallthrough
	case "Agriculture":
		fallthrough
	case "Pharma & Life Sciences":
		fallthrough
	case "Construction":
		fallthrough
	case "Aerospace & Defense":
		fallthrough
	case "Real Estate":
		fallthrough
	case "Restaurant/Food Industry":
		fallthrough
	case "Other":
		*e = TenantServiceGroupCreateVerticalEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TenantServiceGroupCreateVerticalEnum: %v", v)
	}
}

type TenantServiceGroupCreate struct {
	// The tenant service group's display name.
	//
	DisplayName string `json:"display_name"`
	// The TSG ID for this tenant service group's parent.
	//
	ParentID *string `json:"parent_id,omitempty"`
	// The email address of the person or organization that should
	// be contacted for support of this TSG.
	//
	SupportContact *string `json:"support_contact,omitempty"`
	// A token that identifies the business vertical supported by the SASE
	// products managed by this TSG.
	//
	Vertical *TenantServiceGroupCreateVerticalEnum `json:"vertical,omitempty"`
}
