// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TenantServiceGroupUpdateVerticalEnum - A token that identifies the business vertical supported by the SASE
// products managed by this TSG.
type TenantServiceGroupUpdateVerticalEnum string

const (
	TenantServiceGroupUpdateVerticalEnumHighTech                      TenantServiceGroupUpdateVerticalEnum = "High Tech"
	TenantServiceGroupUpdateVerticalEnumEducation                     TenantServiceGroupUpdateVerticalEnum = "Education"
	TenantServiceGroupUpdateVerticalEnumManufacturing                 TenantServiceGroupUpdateVerticalEnum = "Manufacturing"
	TenantServiceGroupUpdateVerticalEnumHospitality                   TenantServiceGroupUpdateVerticalEnum = "Hospitality"
	TenantServiceGroupUpdateVerticalEnumProfessionalAndLegalServices  TenantServiceGroupUpdateVerticalEnum = "Professional & Legal Services"
	TenantServiceGroupUpdateVerticalEnumWholesaleAndRetail            TenantServiceGroupUpdateVerticalEnum = "Wholesale & Retail"
	TenantServiceGroupUpdateVerticalEnumFinance                       TenantServiceGroupUpdateVerticalEnum = "Finance"
	TenantServiceGroupUpdateVerticalEnumTelecommunications            TenantServiceGroupUpdateVerticalEnum = "Telecommunications"
	TenantServiceGroupUpdateVerticalEnumStateAndLocalGovernment       TenantServiceGroupUpdateVerticalEnum = "State & Local Government"
	TenantServiceGroupUpdateVerticalEnumTransportationAndLogistics    TenantServiceGroupUpdateVerticalEnum = "Transportation & Logistics"
	TenantServiceGroupUpdateVerticalEnumFederalGovernment             TenantServiceGroupUpdateVerticalEnum = "Federal Government"
	TenantServiceGroupUpdateVerticalEnumMediaAndEntertainment         TenantServiceGroupUpdateVerticalEnum = "Media & Entertainment"
	TenantServiceGroupUpdateVerticalEnumNonclassifiableEstablishments TenantServiceGroupUpdateVerticalEnum = "Nonclassifiable Establishments"
	TenantServiceGroupUpdateVerticalEnumHealthcare                    TenantServiceGroupUpdateVerticalEnum = "Healthcare"
	TenantServiceGroupUpdateVerticalEnumUtilitiesAndEnergy            TenantServiceGroupUpdateVerticalEnum = "Utilities & Energy"
	TenantServiceGroupUpdateVerticalEnumInsurance                     TenantServiceGroupUpdateVerticalEnum = "Insurance"
	TenantServiceGroupUpdateVerticalEnumAgriculture                   TenantServiceGroupUpdateVerticalEnum = "Agriculture"
	TenantServiceGroupUpdateVerticalEnumPharmaAndLifeSciences         TenantServiceGroupUpdateVerticalEnum = "Pharma & Life Sciences"
	TenantServiceGroupUpdateVerticalEnumConstruction                  TenantServiceGroupUpdateVerticalEnum = "Construction"
	TenantServiceGroupUpdateVerticalEnumAerospaceAndDefense           TenantServiceGroupUpdateVerticalEnum = "Aerospace & Defense"
	TenantServiceGroupUpdateVerticalEnumRealEstate                    TenantServiceGroupUpdateVerticalEnum = "Real Estate"
	TenantServiceGroupUpdateVerticalEnumRestaurantFoodIndustry        TenantServiceGroupUpdateVerticalEnum = "Restaurant/Food Industry"
	TenantServiceGroupUpdateVerticalEnumOther                         TenantServiceGroupUpdateVerticalEnum = "Other"
)

func (e TenantServiceGroupUpdateVerticalEnum) ToPointer() *TenantServiceGroupUpdateVerticalEnum {
	return &e
}

func (e *TenantServiceGroupUpdateVerticalEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "High Tech":
		fallthrough
	case "Education":
		fallthrough
	case "Manufacturing":
		fallthrough
	case "Hospitality":
		fallthrough
	case "Professional & Legal Services":
		fallthrough
	case "Wholesale & Retail":
		fallthrough
	case "Finance":
		fallthrough
	case "Telecommunications":
		fallthrough
	case "State & Local Government":
		fallthrough
	case "Transportation & Logistics":
		fallthrough
	case "Federal Government":
		fallthrough
	case "Media & Entertainment":
		fallthrough
	case "Nonclassifiable Establishments":
		fallthrough
	case "Healthcare":
		fallthrough
	case "Utilities & Energy":
		fallthrough
	case "Insurance":
		fallthrough
	case "Agriculture":
		fallthrough
	case "Pharma & Life Sciences":
		fallthrough
	case "Construction":
		fallthrough
	case "Aerospace & Defense":
		fallthrough
	case "Real Estate":
		fallthrough
	case "Restaurant/Food Industry":
		fallthrough
	case "Other":
		*e = TenantServiceGroupUpdateVerticalEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TenantServiceGroupUpdateVerticalEnum: %v", v)
	}
}

type TenantServiceGroupUpdate struct {
	// The tenant service group's display name.
	//
	DisplayName *string `json:"display_name,omitempty"`
	// The email address of the person or organization that should
	// be contacted for support of this TSG.
	//
	SupportContact *string `json:"support_contact,omitempty"`
	// A token that identifies the business vertical supported by the SASE
	// products managed by this TSG.
	//
	Vertical *TenantServiceGroupUpdateVerticalEnum `json:"vertical,omitempty"`
}
