// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TenantServiceGroupVerticalEnum - A token that identifies the business vertical supported by the SASE
// products managed by this TSG.
type TenantServiceGroupVerticalEnum string

const (
	TenantServiceGroupVerticalEnumHighTech                      TenantServiceGroupVerticalEnum = "High Tech"
	TenantServiceGroupVerticalEnumEducation                     TenantServiceGroupVerticalEnum = "Education"
	TenantServiceGroupVerticalEnumManufacturing                 TenantServiceGroupVerticalEnum = "Manufacturing"
	TenantServiceGroupVerticalEnumHospitality                   TenantServiceGroupVerticalEnum = "Hospitality"
	TenantServiceGroupVerticalEnumProfessionalAndLegalServices  TenantServiceGroupVerticalEnum = "Professional & Legal Services"
	TenantServiceGroupVerticalEnumWholesaleAndRetail            TenantServiceGroupVerticalEnum = "Wholesale & Retail"
	TenantServiceGroupVerticalEnumFinance                       TenantServiceGroupVerticalEnum = "Finance"
	TenantServiceGroupVerticalEnumTelecommunications            TenantServiceGroupVerticalEnum = "Telecommunications"
	TenantServiceGroupVerticalEnumStateAndLocalGovernment       TenantServiceGroupVerticalEnum = "State & Local Government"
	TenantServiceGroupVerticalEnumTransportationAndLogistics    TenantServiceGroupVerticalEnum = "Transportation & Logistics"
	TenantServiceGroupVerticalEnumFederalGovernment             TenantServiceGroupVerticalEnum = "Federal Government"
	TenantServiceGroupVerticalEnumMediaAndEntertainment         TenantServiceGroupVerticalEnum = "Media & Entertainment"
	TenantServiceGroupVerticalEnumNonclassifiableEstablishments TenantServiceGroupVerticalEnum = "Nonclassifiable Establishments"
	TenantServiceGroupVerticalEnumHealthcare                    TenantServiceGroupVerticalEnum = "Healthcare"
	TenantServiceGroupVerticalEnumUtilitiesAndEnergy            TenantServiceGroupVerticalEnum = "Utilities & Energy"
	TenantServiceGroupVerticalEnumInsurance                     TenantServiceGroupVerticalEnum = "Insurance"
	TenantServiceGroupVerticalEnumAgriculture                   TenantServiceGroupVerticalEnum = "Agriculture"
	TenantServiceGroupVerticalEnumPharmaAndLifeSciences         TenantServiceGroupVerticalEnum = "Pharma & Life Sciences"
	TenantServiceGroupVerticalEnumConstruction                  TenantServiceGroupVerticalEnum = "Construction"
	TenantServiceGroupVerticalEnumAerospaceAndDefense           TenantServiceGroupVerticalEnum = "Aerospace & Defense"
	TenantServiceGroupVerticalEnumRealEstate                    TenantServiceGroupVerticalEnum = "Real Estate"
	TenantServiceGroupVerticalEnumRestaurantFoodIndustry        TenantServiceGroupVerticalEnum = "Restaurant/Food Industry"
	TenantServiceGroupVerticalEnumOther                         TenantServiceGroupVerticalEnum = "Other"
)

func (e TenantServiceGroupVerticalEnum) ToPointer() *TenantServiceGroupVerticalEnum {
	return &e
}

func (e *TenantServiceGroupVerticalEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "High Tech":
		fallthrough
	case "Education":
		fallthrough
	case "Manufacturing":
		fallthrough
	case "Hospitality":
		fallthrough
	case "Professional & Legal Services":
		fallthrough
	case "Wholesale & Retail":
		fallthrough
	case "Finance":
		fallthrough
	case "Telecommunications":
		fallthrough
	case "State & Local Government":
		fallthrough
	case "Transportation & Logistics":
		fallthrough
	case "Federal Government":
		fallthrough
	case "Media & Entertainment":
		fallthrough
	case "Nonclassifiable Establishments":
		fallthrough
	case "Healthcare":
		fallthrough
	case "Utilities & Energy":
		fallthrough
	case "Insurance":
		fallthrough
	case "Agriculture":
		fallthrough
	case "Pharma & Life Sciences":
		fallthrough
	case "Construction":
		fallthrough
	case "Aerospace & Defense":
		fallthrough
	case "Real Estate":
		fallthrough
	case "Restaurant/Food Industry":
		fallthrough
	case "Other":
		*e = TenantServiceGroupVerticalEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TenantServiceGroupVerticalEnum: %v", v)
	}
}

// TenantServiceGroup - Successful response.
type TenantServiceGroup struct {
	// The tenant service group's display name.
	//
	DisplayName *string `json:"display_name,omitempty"`
	// The tenant service group's ID.
	ID string `json:"id"`
	// The TSG ID for this tenant service group's parent.
	//
	ParentID *string `json:"parent_id,omitempty"`
	// The email address of the person or organization that should
	// be contacted for support of this TSG.
	//
	SupportContact *string `json:"support_contact,omitempty"`
	// A token that identifies the business vertical supported by the SASE
	// products managed by this TSG.
	//
	Vertical *TenantServiceGroupVerticalEnum `json:"vertical,omitempty"`
}
