// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TenantServiceGroupCreateVertical - A token that identifies the business vertical supported by the SASE
// products managed by this TSG.
type TenantServiceGroupCreateVertical string

const (
	TenantServiceGroupCreateVerticalHighTech                      TenantServiceGroupCreateVertical = "High Tech"
	TenantServiceGroupCreateVerticalEducation                     TenantServiceGroupCreateVertical = "Education"
	TenantServiceGroupCreateVerticalManufacturing                 TenantServiceGroupCreateVertical = "Manufacturing"
	TenantServiceGroupCreateVerticalHospitality                   TenantServiceGroupCreateVertical = "Hospitality"
	TenantServiceGroupCreateVerticalProfessionalAndLegalServices  TenantServiceGroupCreateVertical = "Professional & Legal Services"
	TenantServiceGroupCreateVerticalWholesaleAndRetail            TenantServiceGroupCreateVertical = "Wholesale & Retail"
	TenantServiceGroupCreateVerticalFinance                       TenantServiceGroupCreateVertical = "Finance"
	TenantServiceGroupCreateVerticalTelecommunications            TenantServiceGroupCreateVertical = "Telecommunications"
	TenantServiceGroupCreateVerticalStateAndLocalGovernment       TenantServiceGroupCreateVertical = "State & Local Government"
	TenantServiceGroupCreateVerticalTransportationAndLogistics    TenantServiceGroupCreateVertical = "Transportation & Logistics"
	TenantServiceGroupCreateVerticalFederalGovernment             TenantServiceGroupCreateVertical = "Federal Government"
	TenantServiceGroupCreateVerticalMediaAndEntertainment         TenantServiceGroupCreateVertical = "Media & Entertainment"
	TenantServiceGroupCreateVerticalNonclassifiableEstablishments TenantServiceGroupCreateVertical = "Nonclassifiable Establishments"
	TenantServiceGroupCreateVerticalHealthcare                    TenantServiceGroupCreateVertical = "Healthcare"
	TenantServiceGroupCreateVerticalUtilitiesAndEnergy            TenantServiceGroupCreateVertical = "Utilities & Energy"
	TenantServiceGroupCreateVerticalInsurance                     TenantServiceGroupCreateVertical = "Insurance"
	TenantServiceGroupCreateVerticalAgriculture                   TenantServiceGroupCreateVertical = "Agriculture"
	TenantServiceGroupCreateVerticalPharmaAndLifeSciences         TenantServiceGroupCreateVertical = "Pharma & Life Sciences"
	TenantServiceGroupCreateVerticalConstruction                  TenantServiceGroupCreateVertical = "Construction"
	TenantServiceGroupCreateVerticalAerospaceAndDefense           TenantServiceGroupCreateVertical = "Aerospace & Defense"
	TenantServiceGroupCreateVerticalRealEstate                    TenantServiceGroupCreateVertical = "Real Estate"
	TenantServiceGroupCreateVerticalRestaurantFoodIndustry        TenantServiceGroupCreateVertical = "Restaurant/Food Industry"
	TenantServiceGroupCreateVerticalOther                         TenantServiceGroupCreateVertical = "Other"
)

func (e TenantServiceGroupCreateVertical) ToPointer() *TenantServiceGroupCreateVertical {
	return &e
}

func (e *TenantServiceGroupCreateVertical) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "High Tech":
		fallthrough
	case "Education":
		fallthrough
	case "Manufacturing":
		fallthrough
	case "Hospitality":
		fallthrough
	case "Professional & Legal Services":
		fallthrough
	case "Wholesale & Retail":
		fallthrough
	case "Finance":
		fallthrough
	case "Telecommunications":
		fallthrough
	case "State & Local Government":
		fallthrough
	case "Transportation & Logistics":
		fallthrough
	case "Federal Government":
		fallthrough
	case "Media & Entertainment":
		fallthrough
	case "Nonclassifiable Establishments":
		fallthrough
	case "Healthcare":
		fallthrough
	case "Utilities & Energy":
		fallthrough
	case "Insurance":
		fallthrough
	case "Agriculture":
		fallthrough
	case "Pharma & Life Sciences":
		fallthrough
	case "Construction":
		fallthrough
	case "Aerospace & Defense":
		fallthrough
	case "Real Estate":
		fallthrough
	case "Restaurant/Food Industry":
		fallthrough
	case "Other":
		*e = TenantServiceGroupCreateVertical(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TenantServiceGroupCreateVertical: %v", v)
	}
}

type TenantServiceGroupCreate struct {
	// The tenant service group's display name.
	//
	DisplayName string `json:"display_name"`
	// The TSG ID for this tenant service group's parent.
	//
	ParentID *string `json:"parent_id,omitempty"`
	// The email address of the person or organization that should
	// be contacted for support of this TSG.
	//
	SupportContact *string `json:"support_contact,omitempty"`
	// A token that identifies the business vertical supported by the SASE
	// products managed by this TSG.
	//
	Vertical *TenantServiceGroupCreateVertical `json:"vertical,omitempty"`
}
