// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TenantServiceGroupVertical - A token that identifies the business vertical supported by the SASE
// products managed by this TSG.
type TenantServiceGroupVertical string

const (
	TenantServiceGroupVerticalHighTech                      TenantServiceGroupVertical = "High Tech"
	TenantServiceGroupVerticalEducation                     TenantServiceGroupVertical = "Education"
	TenantServiceGroupVerticalManufacturing                 TenantServiceGroupVertical = "Manufacturing"
	TenantServiceGroupVerticalHospitality                   TenantServiceGroupVertical = "Hospitality"
	TenantServiceGroupVerticalProfessionalAndLegalServices  TenantServiceGroupVertical = "Professional & Legal Services"
	TenantServiceGroupVerticalWholesaleAndRetail            TenantServiceGroupVertical = "Wholesale & Retail"
	TenantServiceGroupVerticalFinance                       TenantServiceGroupVertical = "Finance"
	TenantServiceGroupVerticalTelecommunications            TenantServiceGroupVertical = "Telecommunications"
	TenantServiceGroupVerticalStateAndLocalGovernment       TenantServiceGroupVertical = "State & Local Government"
	TenantServiceGroupVerticalTransportationAndLogistics    TenantServiceGroupVertical = "Transportation & Logistics"
	TenantServiceGroupVerticalFederalGovernment             TenantServiceGroupVertical = "Federal Government"
	TenantServiceGroupVerticalMediaAndEntertainment         TenantServiceGroupVertical = "Media & Entertainment"
	TenantServiceGroupVerticalNonclassifiableEstablishments TenantServiceGroupVertical = "Nonclassifiable Establishments"
	TenantServiceGroupVerticalHealthcare                    TenantServiceGroupVertical = "Healthcare"
	TenantServiceGroupVerticalUtilitiesAndEnergy            TenantServiceGroupVertical = "Utilities & Energy"
	TenantServiceGroupVerticalInsurance                     TenantServiceGroupVertical = "Insurance"
	TenantServiceGroupVerticalAgriculture                   TenantServiceGroupVertical = "Agriculture"
	TenantServiceGroupVerticalPharmaAndLifeSciences         TenantServiceGroupVertical = "Pharma & Life Sciences"
	TenantServiceGroupVerticalConstruction                  TenantServiceGroupVertical = "Construction"
	TenantServiceGroupVerticalAerospaceAndDefense           TenantServiceGroupVertical = "Aerospace & Defense"
	TenantServiceGroupVerticalRealEstate                    TenantServiceGroupVertical = "Real Estate"
	TenantServiceGroupVerticalRestaurantFoodIndustry        TenantServiceGroupVertical = "Restaurant/Food Industry"
	TenantServiceGroupVerticalOther                         TenantServiceGroupVertical = "Other"
)

func (e TenantServiceGroupVertical) ToPointer() *TenantServiceGroupVertical {
	return &e
}

func (e *TenantServiceGroupVertical) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "High Tech":
		fallthrough
	case "Education":
		fallthrough
	case "Manufacturing":
		fallthrough
	case "Hospitality":
		fallthrough
	case "Professional & Legal Services":
		fallthrough
	case "Wholesale & Retail":
		fallthrough
	case "Finance":
		fallthrough
	case "Telecommunications":
		fallthrough
	case "State & Local Government":
		fallthrough
	case "Transportation & Logistics":
		fallthrough
	case "Federal Government":
		fallthrough
	case "Media & Entertainment":
		fallthrough
	case "Nonclassifiable Establishments":
		fallthrough
	case "Healthcare":
		fallthrough
	case "Utilities & Energy":
		fallthrough
	case "Insurance":
		fallthrough
	case "Agriculture":
		fallthrough
	case "Pharma & Life Sciences":
		fallthrough
	case "Construction":
		fallthrough
	case "Aerospace & Defense":
		fallthrough
	case "Real Estate":
		fallthrough
	case "Restaurant/Food Industry":
		fallthrough
	case "Other":
		*e = TenantServiceGroupVertical(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TenantServiceGroupVertical: %v", v)
	}
}

// TenantServiceGroup - Successful response.
type TenantServiceGroup struct {
	// The tenant service group's display name.
	//
	DisplayName *string `json:"display_name,omitempty"`
	// The tenant service group's ID.
	ID string `json:"id"`
	// The TSG ID for this tenant service group's parent.
	//
	ParentID *string `json:"parent_id,omitempty"`
	// The email address of the person or organization that should
	// be contacted for support of this TSG.
	//
	SupportContact *string `json:"support_contact,omitempty"`
	// A token that identifies the business vertical supported by the SASE
	// products managed by this TSG.
	//
	Vertical *TenantServiceGroupVertical `json:"vertical,omitempty"`
}
