// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"pan-sase-tenancy/internal/sdk/pkg/models/shared"
)

func (r *TenantServiceGroupResourceModel) ToCreateSDKType() *shared.TenantServiceGroupCreate {
	displayName := r.DisplayName.ValueString()
	parentID := new(string)
	if !r.ParentID.IsUnknown() && !r.ParentID.IsNull() {
		*parentID = r.ParentID.ValueString()
	} else {
		parentID = nil
	}
	supportContact := new(string)
	if !r.SupportContact.IsUnknown() && !r.SupportContact.IsNull() {
		*supportContact = r.SupportContact.ValueString()
	} else {
		supportContact = nil
	}
	vertical := new(shared.TenantServiceGroupCreateVertical)
	if !r.Vertical.IsUnknown() && !r.Vertical.IsNull() {
		*vertical = shared.TenantServiceGroupCreateVertical(r.Vertical.ValueString())
	} else {
		vertical = nil
	}
	out := shared.TenantServiceGroupCreate{
		DisplayName:    displayName,
		ParentID:       parentID,
		SupportContact: supportContact,
		Vertical:       vertical,
	}
	return &out
}

func (r *TenantServiceGroupResourceModel) ToGetSDKType() *shared.TenantServiceGroupCreate {
	out := r.ToCreateSDKType()
	return out
}

func (r *TenantServiceGroupResourceModel) ToUpdateSDKType() *shared.TenantServiceGroupCreate {
	out := r.ToCreateSDKType()
	return out
}

func (r *TenantServiceGroupResourceModel) ToDeleteSDKType() *shared.TenantServiceGroupCreate {
	out := r.ToCreateSDKType()
	return out
}

func (r *TenantServiceGroupResourceModel) RefreshFromGetResponse(resp *shared.TenantServiceGroup) {
	if resp.DisplayName != nil {
		r.DisplayName = types.StringValue(*resp.DisplayName)
	} else {
		r.DisplayName = types.StringNull()
	}
	r.ID = types.StringValue(resp.ID)
	if resp.ParentID != nil {
		r.ParentID = types.StringValue(*resp.ParentID)
	} else {
		r.ParentID = types.StringNull()
	}
	if resp.SupportContact != nil {
		r.SupportContact = types.StringValue(*resp.SupportContact)
	} else {
		r.SupportContact = types.StringNull()
	}
	if resp.Vertical != nil {
		r.Vertical = types.StringValue(string(*resp.Vertical))
	} else {
		r.Vertical = types.StringNull()
	}
}

func (r *TenantServiceGroupResourceModel) RefreshFromCreateResponse(resp *shared.TenantServiceGroup) {
	r.RefreshFromGetResponse(resp)
}

func (r *TenantServiceGroupResourceModel) RefreshFromUpdateResponse(resp *shared.TenantServiceGroup) {
	r.RefreshFromGetResponse(resp)
}
