// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"pan-sase-tenancy/internal/sdk/pkg/models/shared"
)

type PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildrenRequest struct {
	// If `true`, return the entire descendent hierarchy.
	// If `false`, return only the immediate children of the
	// TSG identified in this call's path. Default is
	// `false`.
	//
	Hierarchy *bool `queryParam:"style=form,explode=true,name=hierarchy"`
	// Indicates if the TSG used to generate this hierarchy is
	// included in the resulting TSG list. `true` to include
	// self. Default is `false`.
	//
	IncludeSelf *bool `queryParam:"style=form,explode=true,name=include_self"`
	// A unique identifier for the tenant service group.
	//
	TsgID string `pathParam:"style=simple,explode=false,name=tsg_id"`
}

// PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildren200ApplicationJSON - Successful response.
type PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildren200ApplicationJSON struct {
	// Total count of the items
	Count int64                       `json:"count"`
	Items []shared.TenantServiceGroup `json:"items"`
}

type PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildrenResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response.
	PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildren200ApplicationJSONObject *PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildren200ApplicationJSON
}
