// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSecurity struct {
	Bearer string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

// PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum - Identifies the response structure's sort order:
//
// * `asc` : From root to leaf.
// * `desc` : From leaf to root.
type PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum string

const (
	PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnumAsc  PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum = "asc"
	PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnumDesc PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum = "desc"
)

func (e PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum) ToPointer() *PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum {
	return &e
}

func (e *PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum: %v", v)
	}
}

type PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsRequest struct {
	// Provide a comma-separated list of fields you want returned.
	//
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// Indicates if the TSG used to generate this hierarchy is
	// included in the resulting TSG list. `true` to include
	// self. Default is `false`.
	//
	IncludeSelf *bool `queryParam:"style=form,explode=true,name=include_self"`
	// Identifies the response structure's sort order:
	//
	// * `asc` : From root to leaf.
	// * `desc` : From leaf to root.
	//
	Sort *PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsSortEnum `queryParam:"style=form,explode=true,name=sort"`
	// A unique identifier for the tenant service group.
	//
	TsgID string `pathParam:"style=simple,explode=false,name=tsg_id"`
}

// PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestors200ApplicationJSON - Successful response.
type PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestors200ApplicationJSON struct {
	// Total count of the items
	Count int64                       `json:"count"`
	Items []shared.TenantServiceGroup `json:"items"`
}

type PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestorsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response.
	PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestors200ApplicationJSONObject *PostTenancyV1TenantServiceGroupsTsgIDOperationsListAncestors200ApplicationJSON
}
