// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type PostTenancyV1TenantServiceGroupsSecurity struct {
	Bearer string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type PostTenancyV1TenantServiceGroupsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response.
	TenantServiceGroup *shared.TenantServiceGroup
}
